# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Create GH Pages

on:
  push:
    branches: ["add-gh-action"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4
      - name: Generate branch GH Page
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
      - run: npm install
      - run: npm run deploy-branch
