# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Create GH Pages

on:
  push:
    branches: ["add-gh-action"]

  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "."

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
      - name: Install Packages
        run: npm install
        working-directory: ${{ env.BUILD_PATH }}
      - name: Build Swagger
        run: |
          npm run swagger bundle --        -o swagger.json
          npm run swagger bundle -- --yaml -o swagger.yaml
        working-directory: ${{ env.BUILD_PATH }}
      - name: Copy Index
        run: cp web/index.html ./
        working-directory: ${{ env.BUILD_PATH }}
      - name: Replace swagger.json link
        # run: sed -i 's/http:\/\/petstore.swagger.io\/v2\/swagger.json/..\/swagger.json/g' swagger-ui/index.html
        run: ls -al
        working-directory: ${{ env.BUILD_PATH }}
